### ISSUE TITLE
Aliasing of collision meshes

### ISSUE THREAD

**Issue by Shinmera** [eoineoineoin/glTF_Physics_Blender_Exporter#10]
Right now if I create, say, a monkey and set its collision shape to mesh, then copy-paste the monkey a bunch of times and export it, the resulting glb will have a separate collision shape and mesh reference for each of the monkeys. I'm not sure how feasible it is to alias things to save on space, but it would definitely be really nice not to have direct duplicates like this.

**Comment by eoineoineoin** [comment]
This is actually built-in to the glTF exporter. However, I think you're seeing a difference between the kinds of copy operations blender does.

If you "Object -> Duplicate Object", Blender will make a deep copy of the whole object. In that case, you get two "duplicate" objects out (glTF.mesh, not just collision_shapes.shape). There's nothing in the exporter that knows they have the same contents, and in Blender, if you modify one mesh, the other will be unaffected.

However, if you "Object -> Duplicate Object Linked", Blender will make a shallow copy of that object. If you modify one mesh, you'll see that the other mesh is updated at the same time. Now, when you export that file, the objects _will_ be de-duplicated - you'll see two nodes, but they'll both reference the same glTF.mesh and the same collision_shapes.shape.

**Comment by Shinmera** [comment]
Ah, dang. I guess  I was expecting the default behaviour to make a link rather than a deep copy. My bad once again, then. Thanks for clearing it up!
