### ISSUE TITLE
Upstream Spec Changes

### ISSUE THREAD

**Issue by Shinmera** [eoineoineoin/glTF_Physics_Blender_Exporter#3]
So it looks like currently this extension has drifted a bit from the upstream spec that's being ratified. Most notably the prefix has changed from KHR to MSFT, and some other minor property names have changed as well.

Would you be open to a PR to change these names in the exporter to reflect the upstream?

**Comment by eoineoineoin** [comment]
The KHR version is actually the most recent version and has had additional feedback applied which are not in the MSFT version. The PR in the Khronos repo hasn't been updated just to avoid noise while we finish the last few pieces, but you can see the history in https://github.com/eoineoineoin/glTF_Physics/commits/master

An earlier version of this plugin does use the MSFT prefix (but I suspect that's not what you want!):
https://github.com/eoineoineoin/glTF_Physics_Blender_Exporter/tree/hk_users

**Comment by Shinmera** [comment]
Ok, I'll update my parser to reference that spec then, thanks!
