### ISSUE TITLE
Blender 4 compat

### ISSUE THREAD

**Issue by Skyedra** [eoineoineoin/glTF_Physics_Blender_Exporter#5]
Love the idea of being able to define physics right inside blender so I checked out your plugin, but unfortunately could not get it to run in blender 4 (either MSFT or KHR versions).  When attempting to activate:

![image](https://github.com/eoineoineoin/glTF_Physics_Blender_Exporter/assets/22365940/9892cc45-32ce-4756-b1dd-490c16ce8f50)

**Comment by Skyedra** [comment]
Just needed to change line 541 to remove the 3D: `self.shader = gpu.shader.from_builtin('UNIFORM_COLOR')`

**Comment by eoineoineoin** [comment]
Thanks. This has been fixed on the latest HEAD and is incorporated into the 0.2.0 release package.
