### ISSUE TITLE
Collision Collections Aren't Exported

### ISSUE THREAD

**Issue by Shinmera** [eoineoineoin/glTF_Physics_Blender_Exporter#6]
It seems like the collision collections in Blender aren't yet translated to different systems in the resulting glb. Even when I set some physics entities to a different collection, the exported file still only contains a `System_0`.

**Comment by eoineoineoin** [comment]
Hm, that sounds unusual. It should work, and the sample assets do have non-default collections. Can you share how the asset is setup? From a quick test here, a body with this configuration:

![image](https://github.com/eoineoineoin/glTF_Physics_Blender_Exporter/assets/1676295/642a9843-b97c-4ccc-b0f7-db1722e709ee)

Does seem to result in the expected filter in the exported glTF:

![image](https://github.com/eoineoineoin/glTF_Physics_Blender_Exporter/assets/1676295/9b241537-c549-4e19-9250-636cc6b224ab)

**Comment by Shinmera** [comment]
I have a node with the collection set to the second one, collider set to compound parent, and a child node with the collision geometry I need. Then a second with the same but the collection set to the first one. Maybe the compound parent is messing with it?

**Comment by eoineoineoin** [comment]
Yeah, that sounds like it. Blender hides the collision collections for children of a compound parent. You can workaround that by removing the child from the parent, configuring the collections and then re-parenting; however, I've added a new release which displays the collections settings regardless (not super for UX, but hopefully works for you.)
