### ISSUE TITLE
Cone colliders are exported as cylinders

### ISSUE THREAD

**Issue by Shinmera** [eoineoineoin/glTF_Physics_Blender_Exporter#9]
Unless the khr extension gains cones as primitives, it would probably be better to convert the blender cone primitives to a convex mesh. A cylinder is quite inaccurate of a representation.

**Comment by eoineoineoin** [comment]
So, you _should_ see that a Blender CONE is exported as a cylinder with a zero radius on one end:

```
		"KHR_collision_shapes":{
			"shapes":[
				{
					"type":"cylinder",
					"cylinder":{
						"height":2,
						"radiusBottom":1,
						"radiusTop":0
					}
				}
			]
		},
```

Is that not the case?

I appreciate the name might be a little confusing - cylinders and cones are both special-cases of a conic. In the USD working group (which already had cones and cylinders special-cased), we settled on adding the radii parameters to cylinders; then, we kept the glTF spec in-line with USD for compatibility.

Also, saw your SBCL blog post linked from HN recently - cool stuff!

**Comment by Shinmera** [comment]
Oh! Dang. I must have missed that and simply ignored it in my parser when I was upgrading spec numbers. My bad!

And thanks! I'll probably make another entry at some point to talk about the 3D capabilities of the engine. The glTF stuff has been paramount to making this work at all, since I really don't have the capacity to build an editor on top of everything else.
